version: '3.8'

networks:
  mongo-network:
    driver: bridge

services:
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    networks:
      - mongo-network
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongouser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mongopwd
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4.3
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mongo-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongouser
      - MONGO_INITDB_ROOT_PASSWORD=mongopwd

volumes:
  mongo_data:


